### ISSUE TITLE
isTestsResultRelevant throws 404 when jobId contains slash '/'

### ISSUE THREAD

**Issue by banduric** [MicroFocus/octane-ci-java-sdk#156]
My jobId contains slash '/' - jobId from GitLab
Request to Octane fails with HTTP 404 as the jobId is part of the path to /tests-result-preflight

Should isTestsResultRelevant use query params instead of path parameter for jobId?
Thanks

**Comment by radislavB** [comment]
Hi.
Possibly that your Octane is behind Apache HTTP Server, and there is an issue of [Allowencodedslashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes). In this issue, if there are encoded slashes, it  throw 404.

Please explain how you use CI SDK, is it part of our plugin , or you use CI SDK directly?
Thanks.

**Comment by banduric** [comment]
Hi.
As a part of your GitLab plugin:  [octane-gitlab-service](https://github.com/MicroFocus/octane-gitlab-service)

**Comment by radislavB** [comment]
And your Octane is behind  Apache HTTP Server?

**Comment by radislavB** [comment]
And what is your plugin version?

**Comment by banduric** [comment]
Version used is: 1.1.66
But I have also build octane-gitlab-service from the latests source code. But the result is the exactly the same.

**Comment by radislavB** [comment]
Can you answer about whether your Octane is behind Apache HTTP Server?

**Comment by banduric** [comment]
I need to check Apache HTTP Server with our support admin team. I'm awaiting the response.

**Comment by banduric** [comment]
I have the response: Octane is not behind Apache Proxy. Do you have any suggestion?

**Comment by radislavB** [comment]
Hi.
I pushed additional change to GitLab plugin repo.
Can you try to checkout+compile and check if it fix your issue?

**Comment by banduric** [comment]
It works. Test result was successufully pushed to Octane. Thanks!

**Comment by banduric** [comment]
Additional question: 
Is my understanding correct that current version of the [octane-gitlab-service](https://github.com/MicroFocus/octane-gitlab-service) is not able to push results produced by [octane-cucumber-jvm](https://github.com/MicroFocus/octane-cucumber-jvm) plugin/formatter to Octane?
In another words: Currently I am not able to match Cucumber test result with BDD specification in Ocatane using octane-gitlab-service.
Thanks

**Comment by radislavB** [comment]
unfortunately, its not supported by GitlabService.
Now its supported by jenkins and bamboo plugin

**Comment by radislavB** [comment]
Please add idea to : https://community.microfocus.com/t5/ALM-Octane-Idea-Exchange/idb-p/ALM_Octane_Idea

**Comment by banduric** [comment]
Added: [https://community.microfocus.com/t5/ALM-Octane-Idea-Exchange/Add-support-for-Gherkin-Cucumber-test-in-GitLab-integration/idi-p/2850066](https://community.microfocus.com/t5/ALM-Octane-Idea-Exchange/Add-support-for-Gherkin-Cucumber-test-in-GitLab-integration/idi-p/2850066)
Thanks for propt reaction and help.
